name: plot-IBGE-spatial-dataset

on: [push]

jobs:
    deploy-cloud-runner:
        runs-on: [ubuntu-latest]
        container: docker://dvcorg/cml-py3:latest

        steps:
          - uses: actions/checkout@v2
            

          - name: cml_run
            shell: bash

            env:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
                                       

            run: |
                  
                  
                  echo "## Model run" > report.md
                  
                  pip install -r requirements.txt
                  
                  
                  # main code to run
                  python code/concat_and_plot.py >> report.md
                  
                  
                  # Results
                  echo "## Model plots" >> report.md
                  
                  # plotting in md
                  cml-publish results/figure/Domicilio_V147.png --md --title 'spatial Domicilio V147' >> report.md
                  
                  cml-send-comment report.md